### ISSUE TITLE
这个仓库名字应该是：你的github账号名.github.io

### ISSUE THREAD

**Issue by galaxyv1** [aerfayingbulefish/aerfayingbulefish.github.io#1]
这个仓库名字应该是：你的github账号名.github.io

**Comment by aerfayingbulefish** [comment]
进不去啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "galaxyv1"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 中午12:50
收件人: "aerfayingbulefish/bulefish.github.com"<bulefish.github.com@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [aerfayingbulefish/bulefish.github.com] 这个仓库名字应该是：你的github账号名.github.io (#1)





 
这个仓库名字应该是：你的github账号名.github.io

**Comment by aerfayingbulefish** [comment]
github&nbsp; desktop无法下载




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aerfayingbulefish/bulefish.github.com"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 中午12:50
收件人:&nbsp;"aerfayingbulefish/bulefish.github.com"<bulefish.github.com@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aerfayingbulefish/bulefish.github.com] 这个仓库名字应该是：你的github账号名.github.io (#1)





 
这个仓库名字应该是：你的github账号名.github.io
